### ISSUE TITLE
apply plugin: 'com.novoda.bintray-release'  这个东西报错 特别是Gradle使用高版本的 

### ISSUE THREAD

**Issue by zjianflys** [FreddyChen/KulaKeyboard#2]
https://blog.csdn.net/wo17796452/article/details/106638081/
希望有帮助

**Comment by FreddyChen** [comment]
> https://blog.csdn.net/wo17796452/article/details/106638081/
> 希望有帮助

谢谢，这个是项目上传到jcenter需要的东西，可以删掉
